package com.moretale.domain.story.dto;

import com.moretale.domain.profile.entity.AgeGroup;
import com.moretale.domain.profile.entity.LanguageProficiency;
import com.moretale.domain.profile.entity.StoryPreference;
import jakarta.validation.constraints.NotBlank;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;

// 동화 생성 요청 DTO (확장)
// 기본: 사용자 직접 입력 프롬프트 기반 생성
// 확장: 온보딩 데이터 기반 자동 생성 지원
@Data
@NoArgsConstructor
@AllArgsConstructor
@Builder
public class StoryGenerateRequest {

    // 사용자 입력 프롬프트 (필수)
    @NotBlank(message = "프롬프트를 입력해주세요.")
    private String prompt;

    // 프로필 ID (선택적, 없으면 최신 프로필 사용)
    private Long profileId;

    // 선택적 필드 (프로필 정보를 오버라이드)
    private String childName;
    private String primaryLanguage;
    private String secondaryLanguage;

    // 온보딩 기반 제약 조건
    private AgeGroup ageGroup; // 나이 그룹
    private Integer childAge;   // 실제 나이

    // 언어 숙련도 정보
    private LanguageProficiency firstLanguageProficiency;
    private LanguageProficiency secondLanguageProficiency;
    private LanguageProficiency firstLanguageListening;
    private LanguageProficiency firstLanguageSpeaking;
    private LanguageProficiency secondLanguageListening;
    private LanguageProficiency secondLanguageSpeaking;

    // 이야기 선호도
    private StoryPreference storyPreference;
    private String customStoryPreference;

    // 자동 생성 플래그 (온보딩 직후 자동 생성 여부)
    @Builder.Default
    private Boolean autoGenerated = false;

    // 추천 전래동화 제목 (자동 매핑된 경우)
    private String recommendedTaleTitle;
}
